export enum OrderStatusEnum {
  PENDING = 0,
  ASSIGNED_BUYER = 1,
  ADDITIONAL_INFORMATION_PENDING = 2,
  ORDER_INFORMATION_COMPLETE = 3,
  BUDGETS_IN_PROGRESS = 4,
  BUDGETS_TO_REVIEW = 5,
  BUDGETS_APPROVED = 6,
  PURCHASE_IN_PROGRESS = 7,
  PURCHASE_COMPLETED = 8,
  SHIPPING_IN_PROGRESS = 9,
  COMPLETED = 10,
  CANCELLED = -2,
  REJECTED = -1
}
